poetry.lock: Update isort (5.11.4 -> 5.11.5)
These changes fix the following issue:

```
Processing /build/isort-5.11.4
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/nix/store/5shvyhxgc5km8iljl9xh5sfnmwbw3kas-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/nix/store/5shvyhxgc5km8iljl9xh5sfnmwbw3kas-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/5shvyhxgc5km8iljl9xh5sfnmwbw3kas-python3.10-pip-23.0.1/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/nix/store/xx78pfds0r7150fczmswvv2wnvif7wfp-python3.10-poetry-core-1.5.2/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
      poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
    File "/nix/store/xx78pfds0r7150fczmswvv2wnvif7wfp-python3.10-poetry-core-1.5.2/lib/python3.10/site-packages/poetry/core/factory.py", line 57, in create_poetry
      raise RuntimeError("The Poetry configuration is invalid:\n" + message)
  RuntimeError: The Poetry configuration is invalid:
    - [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
```

This is needed to get our isort dependency to work with newer Poetry
versions. See [1] for the corresponding upstream in isort.

[1]: https://github.com/PyCQA/isort/commit/b3d35702cf92cdeff5b46cc3719f9661c8c91bb2