Sidestep issues installing projectq with 'uv pip install'
While attempting to set up the Python environment for TheAlgorithms/Python,
`uv pip install` fails to install the `projectq` dependency:

  AssertionError: would build wheel with unsupported tag
  ('cp311', 'cp312', 'linux_x86_64')

This error is reproducible outside of the FawltyDeps context, and seems
to be an issue with either `projectq` itself, `uv`, or the combination
of the two.

Our test suite is NOT about installing projectq, but rather about
running FD on TheAlgorithms/Python, so instead of getting bogged down in
irrelevant details concerning its dependencies, let us abandon the
all_reqs_installed experiment altogether. This experiment was already
limited to Linux only, due to other dependency-related issues on Mac and
Windows.

Also, adjust the some_reqs_customized experiment to avoid having to deal
with the projectq dependency (custom mapping FTW!).

One thing we might want to consider for our real_projects test suite is
to stop relying on properly installing third-party dependencies
(that are currently unpinned and therefore will change without warning),
and instead simulate their installation with our `fake_project` test
fixture.